### ISSUE TITLE
Strongly hope to support the stable channel

### ISSUE THREAD

**Issue by mzdk100** [sweet-security/candystore#9]
I am currently looking for a lightweight and efficient key value pair store library, and I am glad to see this, but unfortunately it only supports nightly.
Can it be implemented for a stable channel (in the case of loss of performance)?

**Comment by tomerfiliba** [comment]
done. i expect a considerable performance hit but oh well.
use `--no-default-features`, should work now on stable

**Comment by mzdk100** [comment]
Thank you.
